---
    title: "LTS"
    author: "Alejandro Palacio & Marcelo Botero"
    date: "21/7/2018"
    logo: "/Users/alejandropalacio/Desktop/Logo2.png"
    output: ioslides_presentation

---



```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

#Preparación del entorno de trabajo----

library(tmaptools)
library(tmap)
library(sf)
library(dplyr)


ruta_resultados <-"/Users/alejandropalacio/Documents/GitHub/proBikePolicies/LTS/Resultados/"
load(paste0(ruta_resultados,"Variables_LTS.Rdata"))


#Se generan los mapas de cada variable

mapa_Velocidad<-tm_shape(capa_variables_LTS)+tm_lines(col="Vprom",style ="pretty" ,scale=5 ,palette = "Reds" ,title.col ="Velocidad Promedio", popup.vars = TRUE)+tmap_mode("view")+tm_view(alpha = 1, basemaps = "OpenStreetMap.BlackAndWhite")

mapa_Trafico<-tm_shape(capa_variables_LTS)+tm_lines(col="Trafico",style ="pretty" ,scale=5 ,palette = "Reds" ,title.col ="Velocidad Promedio", popup.vars = TRUE)+tmap_mode("view")+tm_view(alpha = 1, basemaps = "OpenStreetMap.BlackAndWhite")

mapa_Ancho<-tm_shape(capa_variables_LTS)+tm_lines(col="Ancho",style ="pretty" ,scale=5 ,palette = "-RdYlGn" ,title.col ="Velocidad Promedio", popup.vars = TRUE)+tmap_mode("view")+tm_view(alpha = 1, basemaps = "OpenStreetMap.BlackAndWhite")

mapa_Carriles<-tm_shape(capa_variables_LTS)+tm_lines(col="Ancho",style ="pretty" ,scale=5 ,palette = "-RdYlGn" ,title.col ="Velocidad Promedio", popup.vars = TRUE)+tmap_mode("view")+tm_view(alpha = 1, basemaps = "OpenStreetMap.BlackAndWhite")

mapa_CicloRuta<-tm_shape(capa_variables_LTS)+tm_lines(col="Ancho",style ="pretty" ,scale=5 ,palette = "RdYlGn" ,title.col ="Velocidad Promedio", popup.vars = TRUE)+tmap_mode("view")+tm_view(alpha = 1, basemaps = "OpenStreetMap.BlackAndWhite")

mapa_SITP<-tm_shape(capa_variables_LTS)+tm_lines(col="Vprom",style ="pretty" ,scale=5 ,palette = get_brewer_pal("RdYlGn",6,plot = F) ,title.col ="Velocidad Promedio", textNA = "No", colorNA = "Red")+tmap_mode("view")+tm_view(alpha = 1, basemaps = "OpenStreetMap.BlackAndWhite")
```

## Agenda

- Variable Velocidad
- Variable Trafico
- Variable Ancho de la via
- Variable Numero de Carriles
- Variable CicloRuta
- Variable SITP


## Variable Velocidad

```{r,echo = FALSE,fig.align='right'}

mapa_Velocidad

```

## Variable Velocidad

```{r,echo = FALSE,fig.align="center"}

summary(capa_variables_LTS$Vprom)
boxplot(capa_variables_LTS$Vprom, col = "lightskyblue", main="Velocidad", ylab="Velocidad")

```

## Variable Velocidad

```{r,echo = FALSE,fig.align="center"}

hist(capa_variables_LTS$Vprom, col = "lightskyblue", xlab="Velocidad",ylab="Frecuencia", main = "Velocidad Promedio") 

```

## Variable Trafico

```{r,echo = FALSE,fig.align="center"}

mapa_Trafico

```

## Variable Trafico

```{r,echo = FALSE,fig.align="center"}

summary(capa_variables_LTS$Trafico)
boxplot(capa_variables_LTS$Trafico, col = "lightskyblue", main="Trafico", ylab="Trafico")

```

## Variable Trafico

```{r,echo = FALSE,fig.align="center"}

hist(capa_variables_LTS$Trafico, col = "lightskyblue", xlab="Trafico",ylab="Frecuencia", main = "Trafico") 

```






